name: Publish to NPM

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  # tag:
  #   name: Add/update 'latest' tag
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Run latest-tag
  #       uses: EndBug/latest-tag@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest
    #needs: tag

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js for NPM ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"

      - run: |
          echo Install dependencies
          npm ci
          echo Build source
          npm run build --if-present
          echo Delete source directory
          rm -rf src

      - name: Proceed to publishing on NPM if version has been updated
        uses: pascalgn/npm-publish-action@1.3.6
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "true"
          commit_pattern: "^:package: (\\S+)"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    name: Publish on GPR
    runs-on: ubuntu-latest
    needs: tag

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js for GPR ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com/"
          scope: "@waptik"

      - run: |
          echo Install dependencies
          npm ci
          echo Build source
          npm run build --if-present
          echo Delete source directory

      - name: Proceed to publishing on NPM if version has been updated
        uses: pascalgn/npm-publish-action@1.3.6
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "true"
          commit_pattern: "^:package: (\\S+)"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
