# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --ignore-scripts
      - run: npm run build --if-present
        name: Build
      - run: rm -rf src
        name: Delete src directory
      - run: ls
        name: List directories
      - run: npm test
        name: Run tests
        env:
          CI: true

  publish-npm:
    name: Publish on NPM
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
          uses: actions/checkout@v2
      - name: Set up Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 14
            registry-url: 'https://registry.npmjs.org'
      - name: Install and Build
        run: |
            npm ci
            npm run build --if-present
            rm -rf src
            ls
      - name: Proceed to publishing on NPM
        uses: pascalgn/npm-publish-action@1.3.6
        with: 
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "true"
          commit_pattern: "^:package: (\\S+)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    name: Publish on GPR
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
          uses: actions/checkout@v2
      - name: Set up Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 14
            registry-url: https://npm.pkg.github.com/
            scope: "@waptik"
      - name: Install, Build and Change registry
        run: |
            npm ci
            npm run build --if-present
            rm -rf src
            ls
            echo registry=https://npm.pkg.github.com/waptik >> .npmrc
      - name: Proceed to publishing on GPR
        uses: pascalgn/npm-publish-action@1.3.6
        with: 
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "true"
          commit_pattern: "^:package: (\\S+)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_GITHUB_TOKEN}}
