name: npm-publish
on:
  push:
    branches:
      - main # Change this to your default branch

      
env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  CI: true

jobs:
  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build on Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - run: |
          echo Install dependencies
          npm ci
          echo Build source
          npm run build --if-present
          echo Delete source directory
          rm -rf src
          echo List directories & folders
          ls

    - name: Proceed to publishing on NPM if version has been updated
        uses: pascalgn/npm-publish-action@1.3.6
      with:
        tag_name: "v%s"
        tag_message: "v%s"
        create_tag: "true"
        commit_pattern: "^:package: (\\S+)"
      env:
        NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    name: Publish on GPR
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Build on Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com/'
        scope: "@waptik"

    - run: |
          echo Install dependencies
          npm ci
          echo Build source
          npm run build --if-present
          echo Delete source directory
          rm -rf src
          echo List directories & folders
          ls

    - name: Proceed to publishing on GPR if version has been updated
        uses: pascalgn/npm-publish-action@1.3.6
      with:
        tag_name: "v%s"
        tag_message: "v%s"
        create_tag: "true"
        commit_pattern: "^:package: (\\S+)"
      env:
        NPM_AUTH_TOKEN: ${{secrets.PUBLISH_GITHUB_TOKEN}}

